# -*- coding: utf-8 -*-
"""Emote2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xrDNcSwrN0d3-Q4TfTx2Oli22xpO_Z7l
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import RMSprop
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('//content//drive')
base_dir1 = "//content//drive//My Drive//Emotion//archive//train/"
base_dir2 = "//content//drive//My Drive//Emotion//archive//test/"
import os
IMG_HEIGHT = 48
IMG_WIDTH = 48
BATCH_SIZE = 831

def preprocess(image, label):
  image = tf.cast(image, tf.float32) / 255.0  # Cast to float32 before dividing
  image = tf.image.rgb_to_grayscale(image) # Convert to grayscale
  return image, label

def img(base_dir):
  if not os.path.exists(base_dir):
    print(f"Error: The specified base directory '{base_dir}' does not exist.")
    print("Please update 'base_dir' to your actual image dataset path.")
  else:
    # Load images from the base directory, assuming subdirectories are class names
    image_dataset = tf.keras.utils.image_dataset_from_directory(
      base_dir,
      labels='inferred',
      label_mode='int',
      image_size=(IMG_HEIGHT, IMG_WIDTH),
      interpolation='nearest',
      batch_size=BATCH_SIZE,
      shuffle=True
    )
  preprocessed_dataset = image_dataset.map(preprocess)
  for images, labels in preprocessed_dataset.take(1):
    print(f"Shape of images in the batch: {images.shape}")
  return images, labels


train_images, train_labels = img(base_dir1)
test_images, test_labels = img(base_dir2)

# convert labels to one hot format
train_labels = keras.utils.to_categorical(train_labels, num_classes=7)
test_labels = keras.utils.to_categorical(test_labels, num_classes=7)

import matplotlib.pyplot as plt
import tensorflow as tf
# Ensure tf is imported for operations like rgb_to_grayscale

def display_sample(num):
  # Print this sample's label
  # train_labels are one-hot encoded, so we need to get the index of the '1'
  label = tf.argmax(train_labels[num]).numpy()

  # The line 'train_images[num] = tf.reshape(48, 48, 48)' caused an InvalidArgumentError.
  # 1. tf.reshape expects the tensor to reshape as its first argument, and the target shape as the second.
  #    Here, it was trying to reshape the scalar `48` into a shape of `(48, 48)`, which has a different number of elements.
  # 2. More importantly, you already have the image in `train_images[num]`, so there's no need to reshape it
  #    or assign a new reshaped tensor back to it in this display function.

  # Get the image tensor (shape: (48, 48, 1) as images are preprocessed to grayscale)
  image_tensor = train_images[num]

  # The image is already grayscale (1 channel) due to preprocessing in the `preprocess` function.
  # Squeeze the last dimension (channel dimension) to make it (H, W) for matplotlib's imshow.
  if image_tensor.shape[-1] == 1:
      image_to_display = tf.squeeze(image_tensor, axis=-1)
  else:
      # Fallback for non-grayscale images, though not expected here given current preprocessing
      image_to_display = image_tensor

  # Convert the TensorFlow tensor to a NumPy array for Matplotlib's imshow
  image_to_display = image_to_display.numpy()

  plt.title(f"Sample: {num} label: {label}")
  plt.imshow(image_to_display, cmap=plt.get_cmap('grey_r')) # Using 'grey_r' for grayscale
  plt.show()

#display_sample(1)
print(train_labels)

display_sample(80)

from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten

model = Sequential()
# Input layer to define the shape of the images (48x48 with 1 color channel for grayscale)
model.add(tf.keras.layers.Input(shape=(IMG_HEIGHT, IMG_WIDTH, 1))) # Changed from 3 to 1

# First Convolutional Block
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))

# Second Convolutional Block
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu', padding='same'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))

# Flatten the output before passing to Dense layers
model.add(Flatten())

# Dense layers
model.add(Dense(1024, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(7, activation='softmax')) # Output layer for 7 classes

model.summary()
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

history = model.fit(train_images, train_labels, batch_size=100, epochs = 100,   verbose=2, validation_data=(test_images, test_labels))

score = model.evaluate(test_images, test_labels, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])